version: 2

models:
  - name: int_page_views
    description: ""
    columns:
      - name: event_id
        description: ""

      - name: created_at_utc
        description: ""

      - name: session_id
        description: ""

      - name: user_id
        description: ""

      - name: page_url
        description: ""


  - name: fct_page_views
    description: ""
    columns:
      - name: event_id
        description: ""

      - name: created_at_utc
        description: ""

      - name: session_id
        description: ""

      - name: user_id
        description: ""

      - name: page_url
        description: ""


        
  